"""Whisper 转录和 LRC 生成核心模块"""
from faster_whisper import WhisperModel
import os
from utils import format_timestamp_lrc, get_output_filename, ensure_output_directory

class WhisperLRCGenerator:
    """使用 faster_whisper 生成 LRC 字幕文件"""

    def __init__(self, model_size="base", device="cpu", compute_type="int8"):
        """初始化 Whisper 模型

        Args:
            model_size (str): 模型大小 (tiny, base, small, medium, large)
            device (str): 设备类型 (cpu, cuda)
            compute_type (str): 计算类型 (int8, float16, float32)
        """
        self.model_size = model_size
        self.device = device
        self.compute_type = compute_type
        self.model = None

    def _load_model(self):
        """加载 Whisper 模型（延迟加载）"""
        if self.model is None:
            print(f"正在加载 Whisper 模型 ({self.model_size})...")
            self.model = WhisperModel(
                self.model_size,
                device=self.device,
                compute_type=self.compute_type
            )
            print("模型加载完成！")

    def transcribe_to_lrc(self, audio_path, output_path=None, language=None,
                          beam_size=5, vad_filter=False):
        """转录音频并生成 LRC 文件

        Args:
            audio_path (str): 音频文件路径
            output_path (str, optional): 输出 LRC 文件路径
            language (str, optional): 语言代码 (如 'zh', 'en')，None 表示自动检测
            beam_size (int): Beam search 大小
            vad_filter (bool): 是否使用语音活动检测过滤静音

        Returns:
            str: 生成的 LRC 文件路径
        """
        # 检查输入文件是否存在
        if not os.path.exists(audio_path):
            raise FileNotFoundError(f"音频文件不存在: {audio_path}")

        # 加载模型
        self._load_model()

        # 确定输出路径
        if output_path is None:
            output_path = get_output_filename(audio_path)

        # 确保输出目录存在
        ensure_output_directory(output_path)

        print(f"正在转录音频: {audio_path}")
        print(f"检测到的语言: {language if language else '自动检测'}")

        # 执行转录
        segments, info = self.model.transcribe(
            audio_path,
            beam_size=beam_size,
            language=language,
            vad_filter=vad_filter
        )

        # 打印检测到的语言信息
        detected_lang = info.language if info.language_probability > 0.5 else "未知"
        print(f"检测到的语言: {detected_lang} (置信度: {info.language_probability:.2f})")

        # 生成 LRC 内容
        lrc_lines = []

        # 添加 LRC 元数据
        lrc_lines.append("[ar:Generated by faster-whisper]")
        lrc_lines.append(f"[al:{os.path.basename(audio_path)}]")
        lrc_lines.append(f"[re:Whisper {self.model_size} model]")
        lrc_lines.append("")  # 空行分隔元数据

        # 处理每个转录片段
        segment_count = 0
        for segment in segments:
            timestamp = format_timestamp_lrc(segment.start)
            text = segment.text.strip()

            # 跳过空文本
            if not text:
                continue

            lrc_lines.append(f"{timestamp}{text}")
            segment_count += 1

            # 打印进度
            if segment_count % 10 == 0:
                print(f"已处理 {segment_count} 个片段...")

        # 写入文件
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lrc_lines))

        print(f"转录完成！共生成 {segment_count} 个时间戳")
        print(f"LRC 文件已保存到: {output_path}")

        return output_path